### ISSUE TITLE
Toggle comments not working properly

### ISSUE THREAD

**Issue by chriscx** [btd/language-scala-plus#1]
There is still an issue with the comment toggle as demonstrated bellow:

![comments not working](https://cloud.githubusercontent.com/assets/2963448/7016159/2af9f00c-dcad-11e4-9c31-2e433e0430a7.gif)

A fix was submitted on the original repo:
https://github.com/jroesch/language-scala/pull/12

**Comment by btd** [comment]
Ok. I will copy it by hands, as it is not mergable, is it ok? Or you can make PR i will merge.

**Comment by btd** [comment]
Published 1.2.2
